import {
  Chair1,
  Chair2,
  Chair3,
  Chair4,
  Sofa1,
  Sofa2,
  Sofa3,
  Sofa4,
  Sofa5,
  Sofa6,
  Sofa7,
  Sofa8,
  Sofa9,
  Sofa10,
  Sofa11,
  Sofa12,
  Sofa13,
  Sofa14,
  Sofa15,
  Sofa16,
  Table1,
  Table2,
  Table3,
  Table4,
  Table5,
  Table6,
  Table7,
  Table8,
  Table9,
  Table10,
  Table11,
  Table12,
  Table13,
  Table14,
  Table15,
  Table16,
  Table17,
  Table18,
  Table19,
  Table20,
  Table21,
  Table22,
  Table23,
  Table24,
  Lamp1,
  Lamp2,
  Lamp3,
  Lamp4,
  Bed1,
  Bed2,
  Bed3,
  Bed4,
  Bed5,
  Bed6,
  Bed7,
  Bed8,
  Bed9,
  Bed10,
  Bed11,
  Bed12,
  Bed13,
  Decor1,
  Decor2,
  Decor3,
  Decor4,
  Decor5,
  Decor6,
  Decor7,
  Decor8,
  Decor9,
  Decor10,
  Decor11,
  Decor12,
  Decor13,
  Decor14,
  Decor15,
  Decor16,
  Decor17,
  Decor18,
  Decor19,
  Decor20,
} from "@/assets";
import { Product } from "@/types";

const popularProducts: Array<Product> = [
  {
    id: 1,
    name: "Armless Solid Dining Chair",
    price: 1250,
    image: Chair1,
    category: "chair",
  },
  {
    id: 2,
    name: "Elle Decor Roux Arm Chair",
    price: 850,
    image: Chair2,
    category: "chair",
  },
  {
    id: 3,
    name: "Elle Decor Roux Arm Chair",
    price: 2000,
    image: Chair3,
    category: "chair",
  },
  {
    id: 4,
    name: "Elle Decor Roux Arm Chair",
    price: 2200,
    image: Chair4,
    category: "chair",
  },
];

const latestProducts: Array<Product> = [
  {
    id: 5,
    name: "Velvet Midnight Natural Sofa",
    price: 1250,
    image: Sofa1,
    category: "sofa",
  },
  {
    id: 6,
    name: "Modern Furniture",
    price: 850,
    image: Sofa2,
    category: "sofa",
  },
  {
    id: 7,
    name: "Modern Furniture Set",
    price: 1500,
    image: Sofa3,
    category: "sofa",
  },
  {
    id: 8,
    name: "Furniture Sofa  Set",
    price: 2200,
    image: Sofa4,
    category: "sofa",
  },
  {
    id: 19,
    name: "Luxury Velvet Sofa",
    price: 1800,
    image: Sofa5,
    category: "sofa",
  },
  {
    id: 20,
    name: "Contemporary Living Room Sofa",
    price: 2100,
    image: Sofa6,
    category: "sofa",
  },
  {
    id: 21,
    name: "Sectional Corner Sofa",
    price: 2800,
    image: Sofa7,
    category: "sofa",
  },
  {
    id: 22,
    name: "Minimalist Design Sofa",
    price: 1900,
    image: Sofa8,
    category: "sofa",
  },
  {
    id: 23,
    name: "Chesterfield Classic Sofa",
    price: 3200,
    image: Sofa9,
    category: "sofa",
  },
  {
    id: 24,
    name: "Scandinavian Style Sofa",
    price: 1650,
    image: Sofa10,
    category: "sofa",
  },
  {
    id: 25,
    name: "Leather Executive Sofa",
    price: 2750,
    image: Sofa11,
    category: "sofa",
  },
  {
    id: 26,
    name: "Modular Sofa System",
    price: 2300,
    image: Sofa12,
    category: "sofa",
  },
  {
    id: 27,
    name: "Rustic Farmhouse Sofa",
    price: 1750,
    image: Sofa13,
    category: "sofa",
  },
  {
    id: 28,
    name: "Mid-Century Modern Sofa",
    price: 2450,
    image: Sofa14,
    category: "sofa",
  },
  {
    id: 29,
    name: "Reclining Comfort Sofa",
    price: 3100,
    image: Sofa15,
    category: "sofa",
  },
  {
    id: 30,
    name: "Elegant Tufted Sofa",
    price: 2650,
    image: Sofa16,
    category: "sofa",
  },
];

const products: Array<Product> = [
  {
    id: 9,
    name: "Modern Table Collection",
    price: 1250,
    image: Table1,
    category: "table",
  },
  {
    id: 10,
    name: "Luxury Gold Accent Table",
    price: 850,
    image: Table2,
    category: "table",
  },
  {
    id: 11,
    name: "Classic Table Collection",
    price: 2000,
    image: Table3,
    category: "table",
  },
  {
    id: 12,
    name: "Furniture & Dining Sets",
    price: 2200,
    image: Table4,
    category: "table",
  },
  {
    id: 13,
    name: "Losh Design Lamp",
    price: 1250,
    image: Lamp1,
    category: "lamp",
  },
  {
    id: 14,
    name: "Ofula Glass Lamp",
    price: 850,
    image: Lamp2,
    category: "lamp",
  },
  {
    id: 15,
    name: "Best Bedroom Lamp",
    price: 1500,
    image: Lamp3,
    category: "lamp",
  },
  {
    id: 16,
    name: "Furniture & Dining Sets",
    price: 2200,
    image: Lamp4,
    category: "lamp",
  },
  {
    id: 17,
    name: "Furniture Sofa  Set",
    price: 2200,
    image: Sofa4,
    category: "sofa",
  },
  {
    id: 18,
    name: "Furniture & Dining Sets",
    price: 2200,
    image: Table4,
    category: "table",
  },
  {
    id: 31,
    name: "Executive Office Table",
    price: 1800,
    image: Table5,
    category: "table",
  },
  {
    id: 32,
    name: "Glass Top Dining Table",
    price: 2400,
    image: Table6,
    category: "table",
  },
  {
    id: 33,
    name: "Rustic Wooden Coffee Table",
    price: 950,
    image: Table7,
    category: "table",
  },
  {
    id: 34,
    name: "Modern Console Table",
    price: 1350,
    image: Table8,
    category: "table",
  },
  {
    id: 35,
    name: "Marble Top Side Table",
    price: 780,
    image: Table9,
    category: "table",
  },
  {
    id: 36,
    name: "Industrial Metal Table",
    price: 1600,
    image: Table10,
    category: "table",
  },
  {
    id: 37,
    name: "Scandinavian Oak Table",
    price: 2100,
    image: Table11,
    category: "table",
  },
  {
    id: 38,
    name: "Vintage Accent Table",
    price: 650,
    image: Table12,
    category: "table",
  },
  {
    id: 39,
    name: "Extendable Dining Table",
    price: 2800,
    image: Table13,
    category: "table",
  },
  {
    id: 40,
    name: "Minimalist End Table",
    price: 420,
    image: Table14,
    category: "table",
  },
  {
    id: 41,
    name: "Farmhouse Kitchen Table",
    price: 1900,
    image: Table15,
    category: "table",
  },
  {
    id: 42,
    name: "Contemporary Bar Table",
    price: 1450,
    image: Table16,
    category: "table",
  },
  {
    id: 43,
    name: "Luxury Mahogany Table",
    price: 3200,
    image: Table17,
    category: "table",
  },
  {
    id: 44,
    name: "Round Pedestal Table",
    price: 1750,
    image: Table18,
    category: "table",
  },
  {
    id: 45,
    name: "Adjustable Height Table",
    price: 1250,
    image: Table19,
    category: "table",
  },
  {
    id: 46,
    name: "Folding Portable Table",
    price: 380,
    image: Table20,
    category: "table",
  },
  {
    id: 47,
    name: "Designer Conference Table",
    price: 4500,
    image: Table21,
    category: "table",
  },
  {
    id: 48,
    name: "Nesting Table Set",
    price: 850,
    image: Table22,
    category: "table",
  },
  {
    id: 49,
    name: "Outdoor Patio Table",
    price: 1100,
    image: Table23,
    category: "table",
  },
  {
    id: 50,
    name: "Artisan Craft Table",
    price: 2600,
    image: Table24,
    category: "table",
  },
  {
    id: 51,
    name: "King Size Platform Bed",
    price: 1850,
    image: Bed1,
    category: "bed",
  },
  {
    id: 52,
    name: "Queen Memory Foam Bed",
    price: 1450,
    image: Bed2,
    category: "bed",
  },
  {
    id: 53,
    name: "Modern Upholstered Bed",
    price: 2200,
    image: Bed3,
    category: "bed",
  },
  {
    id: 54,
    name: "Rustic Wooden Bed Frame",
    price: 1650,
    image: Bed4,
    category: "bed",
  },
  {
    id: 55,
    name: "Luxury Tufted Headboard Bed",
    price: 2800,
    image: Bed5,
    category: "bed",
  },
  {
    id: 56,
    name: "Minimalist Metal Bed",
    price: 950,
    image: Bed6,
    category: "bed",
  },
  {
    id: 57,
    name: "Storage Ottoman Bed",
    price: 2100,
    image: Bed7,
    category: "bed",
  },
  {
    id: 58,
    name: "Scandinavian Style Bed",
    price: 1750,
    image: Bed8,
    category: "bed",
  },
  {
    id: 59,
    name: "Four Poster Canopy Bed",
    price: 3200,
    image: Bed9,
    category: "bed",
  },
  {
    id: 60,
    name: "Adjustable Electric Bed",
    price: 3500,
    image: Bed10,
    category: "bed",
  },
  {
    id: 61,
    name: "Twin Bunk Bed Set",
    price: 1200,
    image: Bed11,
    category: "bed",
  },
  {
    id: 62,
    name: "Daybed with Trundle",
    price: 1400,
    image: Bed12,
    category: "bed",
  },
  {
    id: 63,
    name: "Captain's Bed with Drawers",
    price: 1850,
    image: Bed13,
    category: "bed",
  },
  {
    id: 64,
    name: "Modern Abstract Wall Art",
    price: 280,
    image: Decor1,
    category: "decor",
  },
  {
    id: 65,
    name: "Ceramic Decorative Vase",
    price: 120,
    image: Decor2,
    category: "decor",
  },
  {
    id: 66,
    name: "Vintage Picture Frame Set",
    price: 85,
    image: Decor3,
    category: "decor",
  },
  {
    id: 67,
    name: "Botanical Wall Hanging",
    price: 45,
    image: Decor4,
    category: "decor",
  },
  {
    id: 68,
    name: "Crystal Decorative Bowl",
    price: 180,
    image: Decor5,
    category: "decor",
  },
  {
    id: 69,
    name: "Macrame Wall Tapestry",
    price: 95,
    image: Decor6,
    category: "decor",
  },
  {
    id: 70,
    name: "Floating Wooden Shelves",
    price: 150,
    image: Decor7,
    category: "decor",
  },
  {
    id: 71,
    name: "Decorative Mirror Set",
    price: 220,
    image: Decor8,
    category: "decor",
  },
  {
    id: 72,
    name: "Sculptural Candle Holders",
    price: 75,
    image: Decor9,
    category: "decor",
  },
  {
    id: 73,
    name: "Artificial Succulent Garden",
    price: 65,
    image: Decor10,
    category: "decor",
  },
  {
    id: 74,
    name: "Decorative Throw Pillows",
    price: 55,
    image: Decor11,
    category: "decor",
  },
  {
    id: 75,
    name: "Geometric Wall Clock",
    price: 125,
    image: Decor12,
    category: "decor",
  },
  {
    id: 76,
    name: "Luxury Scented Candles",
    price: 40,
    image: Decor13,
    category: "decor",
  },
  {
    id: 77,
    name: "Decorative Room Divider",
    price: 320,
    image: Decor14,
    category: "decor",
  },
  {
    id: 78,
    name: "Handwoven Basket Set",
    price: 110,
    image: Decor15,
    category: "decor",
  },
  {
    id: 79,
    name: "Minimalist Wall Hooks",
    price: 35,
    image: Decor16,
    category: "decor",
  },
  {
    id: 80,
    name: "Decorative Table Runner",
    price: 45,
    image: Decor17,
    category: "decor",
  },
  {
    id: 81,
    name: "Artistic Sculpture Piece",
    price: 380,
    image: Decor18,
    category: "decor",
  },
  {
    id: 82,
    name: "Bohemian Wind Chimes",
    price: 60,
    image: Decor19,
    category: "decor",
  },
  {
    id: 83,
    name: "Designer Wall Stickers",
    price: 25,
    image: Decor20,
    category: "decor",
  },
];

const allProducts = [...popularProducts, ...latestProducts, ...products];

export { popularProducts, latestProducts, allProducts };
